### ISSUE TITLE
[Security] Workflow build-workflow.yml is using vulnerable action avsm/setup-ocaml

### ISSUE THREAD

**Issue by Freakston** [eldesh/coq-refman-ja#14]
The workflow build-workflow.yml is referencing action avsm/setup-ocaml using references v1.0. However this reference is missing the commit [b8f1dff959a72eacb91e5a31f1b59fa2bb7d82be](https://github.com/avsm/setup-ocaml/commits/b8f1dff959a72eacb91e5a31f1b59fa2bb7d82be) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by eldesh** [comment]
Now, [build-workflow.yml](https://github.com/eldesh/coq-refman-ja/blob/507e5de15549b2f79c0117dbed96d475d64193da/.github/workflows/build-workflow.yml#L28) uses `ocaml/setup-ocaml@v1.1.12` which includes b8f1dff.
Thank you for your info.
